### ISSUE TITLE
[question] possible to make a customized gui media player with this lib ?

### ISSUE THREAD

**Issue by c1ngular** [gen2brain/go-mpv#3]
i was thinking to use this lib to play multiple videos in same window(probably with [glfw](https://github.com/go-gl/glfw) or other go ui toolkits) , it is possible with this lib ?

thanks

**Comment by gen2brain** [comment]
If you are asking about the mpv `render` and `render_gl` APIs, there are no bindings here. There is an old way of embedding the mpv native window via the `wid` option. All that should be documented in MPV header files and documentation.
