### ISSUE TITLE
static linking with mpv?

### ISSUE THREAD

**Issue by BrownNPC** [gen2brain/go-mpv#8]
Your readme says this library supports static linking, but i cannot find any documentation for this, please provide the command required to compile the program with mpv statically linked

**Comment by gen2brain** [comment]
Mpv provides a pkg-config .pc file, the command would be `go build -tags pkgconfig,static` if libmpv is built statically (i.e. `--enable-libmpv-static`). You will not find here documentation on how to compile mpv or how pkg-config works. Note that you can point `PKG_CONFIG_LIBDIR` to your local directory with `mpv.pc` (and dependencies pkg-config includes) where you can do the modifications if needed, but the mpv build system will usually generate the correct `.pc` file.
